module.exports = {
    apps: [
        {
            name: 'elmostafa-backend',
            cwd: './backend',
            script: 'dist/main.js',
            instances: 'max',
            exec_mode: 'cluster',
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
            error_file: './logs/backend-error.log',
            out_file: './logs/backend-out.log',
            merge_logs: true,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            env: {
                NODE_ENV: 'production',
            },
        },
        {
            name: 'elmostafa-frontend',
            cwd: './frontend',
            script: 'npm',
            args: 'start',
            instances: 2,
            exec_mode: 'cluster',
            autorestart: true,
            watch: false,
            max_memory_restart: '1G',
            error_file: './logs/frontend-error.log',
            out_file: './logs/frontend-out.log',
            merge_logs: true,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            env: {
                NODE_ENV: 'production',
                PORT: 3000,
                HOSTNAME: '0.0.0.0',
            },
        },
    ],
};
