import { QueryRunner } from 'typeorm';
import { insertIgnore } from './helpers';

export async function seedMolds(qr: QueryRunner) {
  await insertIgnore(qr, 'molds', [
    {
      id: 1,
      name: 'Chair Mold',
      product_id: 6,
      product_weight: 1.8,
      cavities: 2,
      status: 'GOOD',
      current_shots: 15000,
      price: 85000,
      max_shots: 500000,
      total_production_cycles: 7500,
      life_cycle_status: 'good',
      notes: 'قالب كرسي 501',
    },
    {
      id: 2,
      name: 'Table Top Mold',
      product_id: 7,
      product_weight: 2.5,
      cavities: 1,
      status: 'GOOD',
      current_shots: 8000,
      price: 95000,
      max_shots: 400000,
      total_production_cycles: 8000,
      life_cycle_status: 'good',
      notes: 'قالب سطح طاولة 60×60',
    },
    {
      id: 3,
      name: 'Storage Box Mold',
      product_id: 8,
      product_weight: 1.2,
      cavities: 2,
      status: 'GOOD',
      current_shots: 22000,
      price: 65000,
      max_shots: 600000,
      total_production_cycles: 11000,
      life_cycle_status: 'good',
      notes: 'قالب صندوق تخزين 40 لتر',
    },
    {
      id: 4,
      name: 'Bucket Mold',
      product_id: 9,
      product_weight: 0.8,
      cavities: 4,
      status: 'GOOD',
      current_shots: 35000,
      price: 55000,
      max_shots: 700000,
      total_production_cycles: 8750,
      life_cycle_status: 'good',
      notes: 'قالب دلو 20 لتر',
    },
    {
      id: 5,
      name: 'Bottle Cap Mold',
      product_id: 11,
      product_weight: 0.003,
      cavities: 16,
      status: 'GOOD',
      current_shots: 120000,
      price: 45000,
      max_shots: 1000000,
      total_production_cycles: 7500,
      life_cycle_status: 'good',
      notes: 'قالب غطاء قنينة',
    },
    {
      id: 6,
      name: 'Crate Mold',
      product_id: 12,
      product_weight: 1.5,
      cavities: 1,
      status: 'GOOD',
      current_shots: 5000,
      price: 78000,
      max_shots: 350000,
      total_production_cycles: 5000,
      life_cycle_status: 'good',
      notes: 'قالب صندوق 40×30',
    },
  ]);
}
