import { QueryRunner } from 'typeorm';
import { insertIgnore } from './helpers';

export async function seedOrders(qr: QueryRunner) {
  await insertIgnore(qr, 'purchase_orders', [
    {
      id: 1,
      supplier_id: 1,
      invoice_number: 'PO-2026-001',
      total_amount: 17000,
      status: 'COMPLETED',
      notes: 'طلب HDPE',
      order_date: '2026-05-01',
      currency_code: 'USD',
      exchange_rate: 30.5,
      total_amount_foreign: 557.38,
      freight_cost: 500,
      customs_percent: 5,
      commission_percent: 2,
      total_landed_cost: 18500,
      total_weight_kg: 2000,
    },
    {
      id: 2,
      supplier_id: 3,
      invoice_number: 'PO-2026-002',
      total_amount: 14000,
      status: 'COMPLETED',
      notes: 'طلب PP',
      order_date: '2026-05-10',
      currency_code: 'EGP',
      exchange_rate: 1,
      total_amount_foreign: 14000,
      freight_cost: 0,
      customs_percent: 0,
      commission_percent: 0,
      total_landed_cost: 14000,
      total_weight_kg: 2000,
    },
    {
      id: 3,
      supplier_id: 2,
      invoice_number: 'PO-2026-003',
      total_amount: 9000,
      status: 'PENDING',
      notes: 'طلب LDPE',
      order_date: '2026-05-20',
      currency_code: 'USD',
      exchange_rate: 30.5,
      total_amount_foreign: 295.08,
      freight_cost: 300,
      customs_percent: 5,
      commission_percent: 1.5,
      total_landed_cost: 10000,
      total_weight_kg: 1000,
    },
  ]);

  await insertIgnore(qr, 'purchase_order_items', [
    {
      id: 1,
      order_id: 1,
      product_id: 1,
      quantity: 2000,
      price: 8.5,
      total: 17000,
    },
    {
      id: 2,
      order_id: 2,
      product_id: 2,
      quantity: 2000,
      price: 7.0,
      total: 14000,
    },
    {
      id: 3,
      order_id: 3,
      product_id: 5,
      quantity: 1000,
      price: 9.0,
      total: 9000,
    },
  ]);

  await insertIgnore(qr, 'sales_orders', [
    {
      id: 1,
      customer_id: 1,
      total_amount: 13500,
      status: 'COMPLETED',
      notes: 'طلب كراسي',
      order_date: '2026-05-05',
    },
    {
      id: 2,
      customer_id: 2,
      total_amount: 13000,
      status: 'COMPLETED',
      notes: 'طلب طاولات وصناديق',
      order_date: '2026-05-10',
    },
    {
      id: 3,
      customer_id: 3,
      total_amount: 3500,
      status: 'PENDING',
      notes: 'طلب قنينات ماء',
      order_date: '2026-05-20',
    },
    {
      id: 4,
      customer_id: 4,
      total_amount: 4400,
      status: 'PENDING',
      notes: 'طلب دلاء',
      order_date: '2026-05-22',
    },
    {
      id: 5,
      customer_id: 5,
      total_amount: 22800,
      status: 'COMPLETED',
      notes: 'طلب متنوع',
      order_date: '2026-05-15',
    },
  ]);

  await insertIgnore(qr, 'sales_order_items', [
    {
      id: 1,
      order_id: 1,
      product_id: 6,
      quantity: 300,
      price: 45.0,
      total: 13500,
    },
    {
      id: 2,
      order_id: 2,
      product_id: 7,
      quantity: 100,
      price: 65.0,
      total: 6500,
    },
    {
      id: 3,
      order_id: 2,
      product_id: 8,
      quantity: 200,
      price: 32.5,
      total: 6500,
    },
    {
      id: 4,
      order_id: 3,
      product_id: 10,
      quantity: 1000,
      price: 3.5,
      total: 3500,
    },
    {
      id: 5,
      order_id: 4,
      product_id: 9,
      quantity: 200,
      price: 22.0,
      total: 4400,
    },
    {
      id: 6,
      order_id: 5,
      product_id: 12,
      quantity: 300,
      price: 38.0,
      total: 11400,
    },
    {
      id: 7,
      order_id: 5,
      product_id: 6,
      quantity: 200,
      price: 45.0,
      total: 9000,
    },
    {
      id: 8,
      order_id: 5,
      product_id: 11,
      quantity: 3000,
      price: 0.8,
      total: 2400,
    },
  ]);
}
