import { QueryRunner } from 'typeorm';
import { insertIgnore } from './helpers';

export async function seedProducts(qr: QueryRunner) {
  await insertIgnore(qr, 'products', [
    {
      id: 1,
      name: 'HDPE Granules',
      sku: 'RM-HDPE-001',
      barcode: '100001',
      cost_price: 8.5,
      selling_price: 12.0,
      category_id: 1,
      warehouse_id: 2,
      unit: 'kg',
      type: 'RAW',
      description: 'حبيبات HDPE عالية الكثافة',
      min_stock: 500,
      weight_grams: 1000,
      raw_material_type: 'HDPE',
    },
    {
      id: 2,
      name: 'PP Granules',
      sku: 'RM-PP-001',
      barcode: '100002',
      cost_price: 7.0,
      selling_price: 10.5,
      category_id: 1,
      warehouse_id: 2,
      unit: 'kg',
      type: 'RAW',
      description: 'حبيبات بولي بروبيلين',
      min_stock: 500,
      weight_grams: 1000,
      raw_material_type: 'PP',
    },
    {
      id: 3,
      name: 'Masterbatch Black',
      sku: 'RM-MB-BLK',
      barcode: '100003',
      cost_price: 15.0,
      selling_price: 22.0,
      category_id: 1,
      warehouse_id: 2,
      unit: 'kg',
      type: 'RAW',
      description: 'ماستر باتش أسود',
      min_stock: 100,
      weight_grams: 1000,
      raw_material_type: 'Masterbatch',
    },
    {
      id: 4,
      name: 'Masterbatch White',
      sku: 'RM-MB-WHT',
      barcode: '100004',
      cost_price: 16.0,
      selling_price: 24.0,
      category_id: 1,
      warehouse_id: 2,
      unit: 'kg',
      type: 'RAW',
      description: 'ماستر باتش أبيض',
      min_stock: 100,
      weight_grams: 1000,
      raw_material_type: 'Masterbatch',
    },
    {
      id: 5,
      name: 'LDPE Granules',
      sku: 'RM-LDPE-001',
      barcode: '100005',
      cost_price: 9.0,
      selling_price: 13.0,
      category_id: 1,
      warehouse_id: 2,
      unit: 'kg',
      type: 'RAW',
      description: 'حبيبات LDPE منخفضة الكثافة',
      min_stock: 300,
      weight_grams: 1000,
      raw_material_type: 'LDPE',
    },
    {
      id: 6,
      name: 'Plastic Chair 501',
      sku: 'FG-CH-501',
      barcode: '200001',
      cost_price: 25.0,
      selling_price: 45.0,
      category_id: 2,
      warehouse_id: 1,
      unit: 'piece',
      type: 'FINISHED',
      description: 'كرسي بلاستيك موديل 501',
      min_stock: 50,
      weight_grams: 1800,
    },
    {
      id: 7,
      name: 'Table Top 60x60',
      sku: 'FG-TT-60',
      barcode: '200002',
      cost_price: 35.0,
      selling_price: 65.0,
      category_id: 2,
      warehouse_id: 1,
      unit: 'piece',
      type: 'FINISHED',
      description: 'سطح طاولة 60×60 سم',
      min_stock: 30,
      weight_grams: 2500,
    },
    {
      id: 8,
      name: 'Storage Box 40L',
      sku: 'FG-SB-40',
      barcode: '200003',
      cost_price: 18.0,
      selling_price: 32.0,
      category_id: 2,
      warehouse_id: 1,
      unit: 'piece',
      type: 'FINISHED',
      description: 'صندوق تخزين 40 لتر',
      min_stock: 40,
      weight_grams: 1200,
    },
    {
      id: 9,
      name: 'Industrial Bucket 20L',
      sku: 'FG-IB-20',
      barcode: '200004',
      cost_price: 12.0,
      selling_price: 22.0,
      category_id: 2,
      warehouse_id: 1,
      unit: 'piece',
      type: 'FINISHED',
      description: 'دلو صناعي 20 لتر',
      min_stock: 60,
      weight_grams: 800,
    },
    {
      id: 10,
      name: 'Water Bottle 1.5L',
      sku: 'FG-WB-15',
      barcode: '200005',
      cost_price: 1.5,
      selling_price: 3.5,
      category_id: 2,
      warehouse_id: 1,
      unit: 'piece',
      type: 'FINISHED',
      description: 'قنينة ماء 1.5 لتر',
      min_stock: 500,
      weight_grams: 35,
    },
    {
      id: 11,
      name: 'Bottle Cap Blue',
      sku: 'FG-BC-BL',
      barcode: '200006',
      cost_price: 0.3,
      selling_price: 0.8,
      category_id: 2,
      warehouse_id: 1,
      unit: 'piece',
      type: 'FINISHED',
      description: 'غطاء قنينة أزرق',
      min_stock: 1000,
      weight_grams: 3,
    },
    {
      id: 12,
      name: 'Crate 40x30',
      sku: 'FG-CR-4030',
      barcode: '200007',
      cost_price: 20.0,
      selling_price: 38.0,
      category_id: 2,
      warehouse_id: 1,
      unit: 'piece',
      type: 'FINISHED',
      description: 'صندوق بلاستيك 40×30 سم',
      min_stock: 25,
      weight_grams: 1500,
    },
  ]);
}
