import { QueryRunner } from 'typeorm';
import { insertIgnore } from './helpers';

export async function seedStock(qr: QueryRunner) {
  await insertIgnore(qr, 'stock', [
    { product_id: 1, warehouse_id: 2, quantity: 1500 },
    { product_id: 2, warehouse_id: 2, quantity: 1800 },
    { product_id: 3, warehouse_id: 2, quantity: 400 },
    { product_id: 4, warehouse_id: 2, quantity: 350 },
    { product_id: 5, warehouse_id: 2, quantity: 800 },
    { product_id: 6, warehouse_id: 1, quantity: 200 },
    { product_id: 7, warehouse_id: 1, quantity: 80 },
    { product_id: 8, warehouse_id: 1, quantity: 150 },
    { product_id: 9, warehouse_id: 1, quantity: 300 },
    { product_id: 10, warehouse_id: 1, quantity: 2500 },
    { product_id: 11, warehouse_id: 1, quantity: 5000 },
    { product_id: 12, warehouse_id: 1, quantity: 100 },
  ]);

  await insertIgnore(qr, 'stock_movements', [
    {
      id: 1,
      product_id: 1,
      warehouse_id: 2,
      type: 'IN',
      quantity: 2000,
      reference_type: 'purchase_order',
      reference_id: 1,
      notes: 'استلام HDPE',
      date: '2026-05-02',
    },
    {
      id: 2,
      product_id: 2,
      warehouse_id: 2,
      type: 'IN',
      quantity: 2000,
      reference_type: 'purchase_order',
      reference_id: 2,
      notes: 'استلام PP',
      date: '2026-05-11',
    },
    {
      id: 3,
      product_id: 5,
      warehouse_id: 2,
      type: 'IN',
      quantity: 1000,
      reference_type: 'purchase_order',
      reference_id: 3,
      notes: 'استلام LDPE',
      date: '2026-05-21',
    },
    {
      id: 4,
      product_id: 6,
      warehouse_id: 1,
      type: 'IN',
      quantity: 500,
      reference_type: 'production',
      reference_id: 1,
      notes: 'إنتاج كراسي',
      date: '2026-05-03',
    },
    {
      id: 5,
      product_id: 6,
      warehouse_id: 1,
      type: 'OUT',
      quantity: 300,
      reference_type: 'sales_order',
      reference_id: 1,
      notes: 'بيع كراسي للشركة الأمل',
      date: '2026-05-05',
    },
    {
      id: 6,
      product_id: 7,
      warehouse_id: 1,
      type: 'IN',
      quantity: 200,
      reference_type: 'production',
      reference_id: 2,
      notes: 'إنتاج طاولات',
      date: '2026-05-06',
    },
    {
      id: 7,
      product_id: 8,
      warehouse_id: 1,
      type: 'IN',
      quantity: 300,
      reference_type: 'production',
      reference_id: 3,
      notes: 'إنتاج صناديق',
      date: '2026-05-07',
    },
    {
      id: 8,
      product_id: 7,
      warehouse_id: 1,
      type: 'OUT',
      quantity: 100,
      reference_type: 'sales_order',
      reference_id: 2,
      notes: 'بيع طاولات',
      date: '2026-05-10',
    },
    {
      id: 9,
      product_id: 8,
      warehouse_id: 1,
      type: 'OUT',
      quantity: 200,
      reference_type: 'sales_order',
      reference_id: 2,
      notes: 'بيع صناديق',
      date: '2026-05-10',
    },
    {
      id: 10,
      product_id: 1,
      warehouse_id: 2,
      type: 'OUT',
      quantity: 500,
      reference_type: 'production',
      reference_id: 1,
      notes: 'صرف HDPE للإنتاج',
      date: '2026-05-03',
    },
    {
      id: 11,
      product_id: 2,
      warehouse_id: 2,
      type: 'OUT',
      quantity: 300,
      reference_type: 'production',
      reference_id: 2,
      notes: 'صرف PP للإنتاج',
      date: '2026-05-06',
    },
    {
      id: 12,
      product_id: 5,
      warehouse_id: 2,
      type: 'OUT',
      quantity: 200,
      reference_type: 'production',
      reference_id: 3,
      notes: 'صرف LDPE للإنتاج',
      date: '2026-05-07',
    },
    {
      id: 13,
      product_id: 9,
      warehouse_id: 1,
      type: 'IN',
      quantity: 500,
      reference_type: 'production',
      reference_id: 4,
      notes: 'إنتاج دلاء',
      date: '2026-05-12',
    },
    {
      id: 14,
      product_id: 10,
      warehouse_id: 1,
      type: 'IN',
      quantity: 3000,
      reference_type: 'production',
      reference_id: 5,
      notes: 'إنتاج قنينات',
      date: '2026-05-14',
    },
    {
      id: 15,
      product_id: 12,
      warehouse_id: 1,
      type: 'IN',
      quantity: 400,
      reference_type: 'production',
      reference_id: 6,
      notes: 'إنتاج صناديق كبيرة',
      date: '2026-05-16',
    },
  ]);
}
