// Role IDs: 1=admin, 2=user, 3=manager, 4=accountant, 5=storekeeper, 6=worker, 7=viewer
export const PAGE_PERMISSIONS: Record<string, number[]> = {
  '/dashboard': [1, 3, 4, 5, 6, 7],
  '/sales': [1, 3],
  '/sales/orders': [1, 3],
  '/sales/customers': [1, 3],
  '/sales/quotes': [1, 3],
  '/sales/returns': [1, 3],
  '/sales/customers/statement': [1, 3],
  '/purchases': [1, 3, 4],
  '/purchases/suppliers': [1, 3, 4],
  '/purchases/suppliers/statement': [1, 3, 4],
  '/purchases/orders': [1, 3, 4],
  '/purchases/returns': [1, 3, 4],
  '/purchases/currencies': [1],
  '/purchases/containers': [1, 3, 4],
  '/inventory2': [1, 3, 5, 6],
  '/inventory2/products': [1, 3, 5, 6],
  '/inventory2/products/bulk-prices': [1, 3, 5],
  '/inventory2/semi-finished': [1, 3, 5, 6],
  '/inventory2/stock': [1, 3, 5, 6],
  '/inventory2/stock/movements': [1, 3, 5, 6],
  '/inventory2/stock/transfer': [1, 3, 5, 6],
  '/inventory2/stock/adjust': [1, 3, 5],
  '/inventory2/warehouses': [1, 3, 5],
  '/manufacturing': [1, 3, 5, 6],
  '/manufacturing/raw-materials': [1, 3, 5, 6],
  '/manufacturing/molds': [1, 3, 5, 6],
  '/manufacturing/machines': [1, 3, 5, 6],
  '/manufacturing/boms': [1, 3, 5, 6],
  '/manufacturing/production': [1, 3, 6],
  '/manufacturing/daily-production': [1, 3, 6],
  '/manufacturing/planning': [1, 3, 5, 6],
  '/manufacturing/schedule': [1, 3, 5, 6],
  '/manufacturing/qc': [1, 3, 5],
  '/manufacturing/assembly': [1, 3, 5, 6],
  '/manufacturing/maintenance': [1, 3, 6],
  '/manufacturing/kiosk': [1, 3, 6],
  '/manufacturing/mrp': [1, 3, 5],
  '/manufacturing/feasibility': [1, 3, 5],
  '/manufacturing/traceability': [1, 3, 5, 6],
  '/manufacturing/fixed-costs': [1, 3, 4],
  '/bom': [1, 3, 5, 6],
  '/assembly': [1, 3, 5, 6],
  '/assembly/production': [1, 3, 6],
  '/assembly/attendance': [1, 3, 6],
  '/assembly/accessories': [1, 3, 5, 6],
  '/assembly/plastic': [1, 3, 5, 6],
  '/assembly/packaging': [1, 3, 5, 6],
  '/assembly/bom': [1, 3, 5, 6],
  '/accounting': [1, 3, 4],
  '/accounting/journal': [1, 3, 4],
  '/hr': [1, 3],
  '/hr/payroll': [1, 3],
  '/hr/employees': [1, 3],
  '/reports': [1, 3, 4, 5, 7],
  '/reports/production': [1, 3, 4, 5, 7],
  '/notifications': [1, 3, 4, 5, 6, 7],
  '/documents': [1, 3, 4, 5, 6, 7],
  '/users': [1],
  '/settings': [1, 3],
  '/audit': [1],
  '/dashboard/control-tower': [1, 3],
};
